### ISSUE TITLE
would you share your data processing code

### ISSUE THREAD

**Issue by MarStarck** [mlfoundations/MINT-1T#11]
like pdf pipeline?

**Comment by anas-awadalla** [comment]
Yes I have a plan to do this but the code needs some reworking before sharing publicly. I will keep you updated on this.

**Comment by anas-awadalla** [comment]
I have uploaded the code for processing a PDF [here](https://gist.github.com/anas-awadalla/2ed732e4897f06601e098035356c9e80). Hope this is helpful.
