### ISSUE TITLE
Related Work 

### ISSUE THREAD

**Issue by TobiasLee** [mlfoundations/MINT-1T#2]
Hi Anas, 

Thank you for your significant contribution with this impressive work.

We would like to kindly draw your attention to our previous work, [Multimodal ArXiv](https://mm-arxiv.github.io/), which also utilizes ArXiv papers to enhance multimodal LLMs. We believe it would be a valuable addition to your related work section.

Thank you for your consideration.

**Comment by TobiasLee** [comment]
Thank you so much for the recognition of our work, and it is totally understandable as we know the pace is so fast in the area :) 

I'm looking forward to your dataset release and we can do something cool based on it!

**Comment by anas-awadalla** [comment]
Update: just made a new arxiv submission with the reference! Thanks again for the reminder.
