### ISSUE TITLE
This is truly a huge amount of data.

### ISSUE THREAD

**Issue by limhasic** [mlfoundations/MINT-1T#7]
But what can I do with this?

Are there any examples of its use?

**Comment by anas-awadalla** [comment]
Hello! The main use case we focus on in the paper is training large multimodal models that reason about both image and text inputs. A few great examples of models that use this data are [MM1](https://machinelearning.apple.com/research/mm1-methods-analysis-insights) and [Idefics2](https://huggingface.co/blog/idefics2).

**Comment by limhasic** [comment]
thank you
